
name: run-all-tests
on:
  pull_request:
    branches:
      - main
      - master
jobs:
  test-application:
    name: Unit-Integration-Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Javier
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Chmod
        run: chmod +x ./gradlew

      - name: Build & Run Gradle test
        run: ./gradlew clean test
