#Hello from other branch

name: run-all-tests
on:
  pull_request:
    branches:
      - main
      - master
jobs:
  test-application:
    name: Unit-Integration-Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Javier
        uses: actions/setup-java@v3
        with:
          distribution: 'coretto'
          java-version: '17'

      - name: Setup Gradle & Test Application
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
